# By default, would enforce { key: value } rather than { :key => value }.
AllCops:
  RunRailsCops: false

# Multi-line method chaining should be done with trailing dots.
Style/DotPosition:
  EnforcedStyle: trailing

HashSyntax:
  EnforcedStyle: ruby19

# Would enforce "-> { }", which we cannot use yet.
Lambda:
  Enabled: false

# ...
LineLength:
  Max: 99

# Relax some of the cops for tests
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - test/node/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb
    - test/node/**/*.rb
