inherit_from: 'https://raw.githubusercontent.com/PublicHealthEngland/ndr_dev_support/master/.rubocop.yml'

Rails:
  Enabled: false

AllCops:
  TargetRailsVersion: 4.2
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: true
